version: '3.8'

services:

  postgres:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/postgres/inventory-service:/data/postgres
      - ./init/postgres/inventory-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: postgres-inventory-local


  postgres-order:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/postgres/order-service:/data/postgres
      - ./init/postgres/order-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: postgres-order-local


  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.ca
      PGADMIN_DEFAULT_PASSWORD: password
    container_name: pgadmin-local
    restart: unless-stopped